In [1]:
import numpy as np
import pandas as pd
import pathlib
import pickle
from behavioral_analysis.utility.builtin_classes.objects import save_object
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [2]:
root_dir = pathlib.Path(r"H:\2026_Letter")

data_root_dir = root_dir / "data"
code_root_dir = root_dir / "code"

data_output_dir = code_root_dir / "data_output"
data_output_dir.mkdir(exist_ok=True, parents=True)

In [3]:
with open(data_root_dir / "fingerprints.pkl", "rb") as f:
    fingerprints, fingerprint_labels = pickle.load(f, encoding='latin1')

fingerprint_labels

OrderedDict([('y_drug',
              array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
                      0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
                      0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,
                      1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
                      1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
                      2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
                      2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
                      3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
                      3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
                      4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
                      5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
                      6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
                      6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
                      6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
                      6,  6,  6,  6,  6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
                      7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,
                      7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,
                      8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
                      8,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9,
                      9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
                     10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11,
                     11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
                     11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
                     11, 11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12,
                     12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
                     13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
                     13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13, 13,
                     13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14,
                     14, 14, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15, 15,
                     15, 15, 15, 15, 15, 15, 15, 15], dtype=int64)),
             ('y_dose',
              array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,
                      1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
                      2,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,
                      4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
                      5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  7,  7,  7,  7,
                      7,  7,  7,  7,  7,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,  8,
                      9,  9,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10, 10, 10, 10, 10, 10,
                     10, 10, 10, 10, 10, 10, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11, 11,
                     11, 12, 12, 12, 12, 12, 12, 12, 12, 12, 13, 13, 13, 13, 13, 13, 13,
                     13, 13, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 14, 15, 15, 15,
                     15, 15, 15, 15, 15, 15, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16, 16,
                     16, 17, 17, 17, 17, 17, 17, 17, 17, 18, 18, 18, 18, 18, 18, 18, 18,
                     18, 18, 18, 18, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 19, 20,
                     20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 21, 21, 21, 21, 21, 21,
                     21, 21, 21, 21, 21, 21, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22, 22,
                     22, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 24, 24, 24, 24,
                     24, 24, 24, 24, 24, 24, 24, 24, 25, 25, 25, 25, 25, 25, 26, 26, 26,
                     26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 27,
                     27, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 28, 29, 29, 29, 29,
                     29, 29, 29, 29, 29, 29, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 31,
                     31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 32, 32, 32, 32, 32, 32, 32,
                     32, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 34, 34, 34, 34,
                     34, 34, 34, 34, 34, 34, 34, 34, 35, 35, 35, 35, 35, 35, 35, 35, 35,
                     35, 35, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 36, 37, 37, 37,
                     37, 37, 37, 37, 37, 37, 37, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38,
                     38, 38, 39, 39, 39, 39, 39, 39, 39, 39, 39, 40, 40, 40, 40, 40, 40,
                     40, 40, 40, 40, 40, 40, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41, 41,
                     41, 42, 42, 42, 42, 42, 42, 42, 42, 42, 43, 43, 43, 43, 43, 43, 43,
                     43, 43, 43, 43, 43, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44, 44,
                     44, 44, 44, 44, 44, 44, 44, 44], dtype=int64)),
             ('y_class',
              array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                     0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                     1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
                     1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                     2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                     2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                     2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                     2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                     2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                     2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
                     3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
                     3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
                     4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
                     4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
                     4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5,
                     5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
                     5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
                     5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
                     5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6,
                     6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6], dtype=int64)),
             ('mouse_names',
              ['C57-10_.1mgkg_alprazolam_11-22-16',
               'C57-11_.1mgkg_alprazolam_11-22-16',
               'C57-12_.1mgkg_alprazolam_11-22-16',
               'C57-1_.1mgkg_alprazolam_11-22-16',
               'C57-2_.1mgkg_alprazolam_11-22-16',
               'C57-3_.1mgkg_alprazolam_11-22-16',
               'C57-4_.1mgkg_alprazolam_11-22-16',
               'C57-5_.1mgkg_alprazolam_11-22-16',
               'C57-6_.1mgkg_alprazolam_11-22-16',
               'C57-7_.1mgkg_alprazolam_11-22-16',
               'C57-8_.1mgkg_alprazolam_11-22-16',
               'C57-9_.1mgkg_alprazolam_11-22-16',
               'C57-10_.25mgkg_alprazolam_11-23-16',
               'C57-11_.25mgkg_alprazolam_11-23-16',
               'C57-12_.25mgkg_alprazolam_11-23-16',
               'C57-1_.25mgkg_alprazolam_11-23-16',
               'C57-2_.25mgkg_alprazolam_11-23-16',
               'C57-3_.25mgkg_alprazolam_11-23-16',
               'C57-4_.25mgkg_alprazolam_11-23-16',
               'C57-5_.25mgkg_alprazolam_11-23-16',
               'C57-6_.25mgkg_alprazolam_11-23-16',
               'C57-7_.25mgkg_alprazolam_11-23-16',
               'C57-8_.25mgkg_alprazolam_11-23-16',
               'C57-9_.25mgkg_alprazolam_11-23-16',
               'C57-10_0.5mgkg_alprazolam_6-15-15',
               'C57-11_0.5mgkg_alprazolam_6-15-15',
               'C57-12_0.5mgkg_alprazolam_6-15-15',
               'C57-1_0.5mgkg_alprazolam_6-15-15',
               'C57-2_0.5mgkg_alprazolam_6-15-15',
               'C57-3_0.5mgkg_alprazolam_6-15-15',
               'C57-4_0.5mgkg_alprazolam_6-15-15',
               'C57-5_0.5mgkg_alprazolam_6-15-15',
               'C57-6_0.5mgkg_alprazolam_6-15-15',
               'C57-7_0.5mgkg_alprazolam_6-15-15',
               'C57-8_0.5mgkg_alprazolam_6-15-15',
               'C57-10_2mgkg_alprazolam_6-22-15',
               'C57-11_2mgkg_alprazolam_6-22-15',
               'C57-12_2mgkg_alprazolam_6-22-15',
               'C57-1_2mgkg_alprazolam_6-22-15',
               'C57-2_2mgkg_alprazolam_6-22-15',
               'C57-3_2mgkg_alprazolam_6-22-15',
               'C57-4_2mgkg_alprazolam_6-22-15',
               'C57-5_2mgkg_alprazolam_6-22-15',
               'C57-7_2mgkg_alprazolam_6-22-15',
               'C57-8_2mgkg_alprazolam_6-22-15',
               'C57-9_2mgkg_alprazolam_6-22-15',
               'C57-10_0.5mgkg_diazepam_5-18-15',
               'C57-11_0.5mgkg_diazepam_5-18-15',
               'C57-12_0.5mgkg_diazepam_5-18-15',
               'C57-1_0.5mgkg_diazepam_5-18-15',
               'C57-2_0.5mgkg_diazepam_5-18-15',
               'C57-3_0.5mgkg_diazepam_5-18-15',
               'C57-4_0.5mgkg_diazepam_5-18-15',
               'C57-5_0.5mgkg_diazepam_5-18-15',
               'C57-6_0.5mgkg_diazepam_5-18-15',
               'C57-8_0.5mgkg_diazepam_5-18-15',
               'C57-9_0.5mgkg_diazepam_5-18-15',
               'C57-10_2mgkg_diazepam_4-7-15',
               'C57-11_2mgkg_diazepam_4-7-15',
               'C57-12_2mgkg_diazepam_4-7-15',
               'C57-1_2mgkg_diazepam_4-7-15',
               'C57-2_2mgkg_diazepam_4-7-15',
               'C57-3_2mgkg_diazepam_4-7-15',
               'C57-4_2mgkg_diazepam_4-7-15',
               'C57-5_2mgkg_diazepam_4-7-15',
               'C57-6_2mgkg_diazepam_4-7-15',
               'C57-7_2mgkg_diazepam_4-7-15',
               'C57-8_2mgkg_diazepam_4-7-15',
               'C57-9_2mgkg_diazepam_4-7-15',
               'C57-10_5mgkg_bupropion_11-25-16',
               'C57-11_5mgkg_bupropion_11-25-16',
               'C57-12_5mgkg_bupropion_11-25-16',
               'C57-1_5mgkg_bupropion_11-25-16',
               'C57-2_5mgkg_bupropion_11-25-16',
               'C57-3_5mgkg_bupropion_11-25-16',
               'C57-4_5mgkg_bupropion_11-25-16',
               'C57-5_5mgkg_bupropion_11-25-16',
               'C57-6_5mgkg_bupropion_11-25-16',
               'C57-7_5mgkg_bupropion_11-25-16',
               'C57-8_5mgkg_bupropion_11-25-16',
               'C57-9_5mgkg_bupropion_11-25-16',
               'C57-10_10mgkg_bupropion_1-31-15',
               'C57-11_10mgkg_bupropion_1-31-15',
               'C57-12_10mgkg_bupropion_1-31-15',
               'C57-1_10mgkg_bupropion_1-31-15',
               'C57-3_10mgkg_bupropion_1-31-15',
               'C57-4_10mgkg_bupropion_1-31-15',
               'C57-6_10mgkg_bupropion_1-31-15',
               'C57-7_10mgkg_bupropion_1-31-15',
               'C57-9_10mgkg_bupropion_1-31-15',
               'C57-10_20mgkg_bupropion_11-25-16',
               'C57-11_20mgkg_bupropion_11-25-16',
               'C57-12_20mgkg_bupropion_11-25-16',
               'C57-1_20mgkg_bupropion_11-25-16',
               'C57-2_20mgkg_bupropion_11-25-16',
               'C57-3_20mgkg_bupropion_11-25-16',
               'C57-4_20mgkg_bupropion_11-25-16',
               'C57-5_20mgkg_bupropion_11-25-16',
               'C57-6_20mgkg_bupropion_11-25-16',
               'C57-7_20mgkg_bupropion_11-25-16',
               'C57-8_20mgkg_bupropion_11-25-16',
               'C57-9_20mgkg_bupropion_11-25-16',
               'C57-10_40mgkg_bupropion_5-11-15',
               'C57-11_40mgkg_bupropion_5-11-15',
               'C57-12_40mgkg_bupropion_5-11-15',
               'C57-1_40mgkg_bupropion_5-11-15',
               'C57-2_40mgkg_bupropion_5-11-15',
               'C57-3_40mgkg_bupropion_5-11-15',
               'C57-4_40mgkg_bupropion_5-11-15',
               'C57-5_40mgkg_bupropion_5-11-15',
               'C57-7_40mgkg_bupropion_5-11-15',
               'C57-8_40mgkg_bupropion_5-11-15',
               'C57-9_40mgkg_bupropion_5-11-15',
               'C57-10_2.5mgkg_phenelzine_5-15-13',
               'C57-11_2.5mgkg_phenelzine_5-15-15',
               'C57-12_2.5mgkg_phenelzine_5-15-15',
               'C57-1_2.5mgkg_phenelzine_5-15-13',
               'C57-2_2.5mgkg_phenelzine_5-15-15',
               'C57-3_2.5mgkg_phenelzine_5-15-15',
               'C57-4_2.5mgkg_phenelzine_5-15-13',
               'C57-5_2.5mgkg_phenelzine_5-15-15',
               'C57-6_2.5mgkg_phenelzine_5-15-15',
               'C57-7_2.5mgkg_phenelzine_5-15-13',
               'C57-8_2.5mgkg_phenelzine_5-15-15',
               'C57-9_2.5mgkg_phenelzine_5-15-15',
               'C57-10_12.5mgkg_phenelzine_5-22-15',
               'C57-11_12.5mgkg_phenelzine_5-22-15',
               'C57-12_12.5mgkg_phenelzine_5-22-15',
               'C57-1_12.5mgkg_phenelzine_5-22-15',
               'C57-2_12.5mgkg_phenelzine_5-22-15',
               'C57-3_12.5mgkg_phenelzine_5-22-15',
               'C57-4_12.5mgkg_phenelzine_5-22-15',
               'C57-5_12.5mgkg_phenelzine_5-22-15',
               'C57-6_12.5mgkg_phenelzine_5-22-15',
               'C57-7_12.5mgkg_phenelzine_5-22-15',
               'C57-8_12.5mgkg_phenelzine_5-22-15',
               'C57-9_12.5mgkg_phenelzine_5-22-15',
               'C57-11_0.25mgkg_chlorpromazine_1-13-15',
               'C57-12_0.25mgkg_chlorpromazine_1-13-15',
               'C57-1_0.25mgkg_chlorpromazine_1-13-15',
               'C57-2_0.25mgkg_chlorpromazine_1-13-15',
               'C57-5_0.25mgkg_chlorpromazine_1-13-15',
               'C57-6_0.25mgkg_chlorpromazine_1-13-15',
               'C57-7_0.25mgkg_chlorpromazine_1-13-15',
               'C57-8_0.25mgkg_chlorpromazine_1-13-15',
               'C57-9_0.25mgkg_chlorpromazine_1-13-15',
               'C57-10_1mgkg_chlorpromazine_5-14-13',
               'C57-11_1mgkg_chlorpromazine_5-14-15',
               'C57-12_1mgkg_chlorpromazine_5-14-15',
               'C57-3_1mgkg_chlorpromazine_5-14-15',
               'C57-4_1mgkg_chlorpromazine_5-14-13',
               'C57-6_1mgkg_chlorpromazine_5-14-15',
               'C57-7_1mgkg_chlorpromazine_5-14-13',
               'C57-8_1mgkg_chlorpromazine_5-14-15',
               'C57-9_1mgkg_chlorpromazine_5-14-15',
               'C57-10_0.25mgkg_clozapine_12-9-14',
               'C57-11_0.25mgkg_clozapine_12-9-14',
               'C57-12_0.25mgkg_clozapine_12-9-14',
               'C57-1_0.25mgkg_clozapine_12-9-14',
               'C57-2_0.25mgkg_clozapine_12-9-14',
               'C57-3_0.25mgkg_clozapine_12-9-14',
               'C57-4_0.25mgkg_clozapine_12-9-14',
               'C57-5_0.25mgkg_clozapine_12-9-14',
               'C57-6_0.25mgkg_clozapine_12-9-14',
               'C57-7_0.25mgkg_clozapine_12-9-14',
               'C57-8_0.25mgkg_clozapine_12-9-14',
               'C57-9_0.25mgkg_clozapine_12-9-14',
               'C57-10_10mgkg_clozapine_5-5-15',
               'C57-11_10mgkg_clozapine_5-5-15',
               'C57-12_10mgkg_clozapine_5-5-15',
               'C57-4_10mgkg_clozapine_5-5-15',
               'C57-5_10mgkg_clozapine_5-5-15',
               'C57-6_10mgkg_clozapine_5-5-15',
               'C57-7_10mgkg_clozapine_5-5-15',
               'C57-8_10mgkg_clozapine_5-5-15',
               'C57-9_10mgkg_clozapine_5-5-15',
               'C57-10_0.1mgkg_haloperidol_2-28-15',
               'C57-11_0.1mgkg_haloperidol_2-28-15',
               'C57-12_0.1mgkg_haloperidol_2-28-15',
               'C57-1_0.1mgkg_haloperidol_2-28-15',
               'C57-2_0.1mgkg_haloperidol_2-28-15',
               'C57-3_0.1mgkg_haloperidol_2-28-15',
               'C57-4_0.1mgkg_haloperidol_2-28-15',
               'C57-5_0.1mgkg_haloperidol_2-28-15',
               'C57-6_0.1mgkg_haloperidol_2-28-15',
               'C57-7_0.1mgkg_haloperidol_2-28-15',
               'C57-8_0.1mgkg_haloperidol_2-28-15',
               'C57-9_0.1mgkg_haloperidol_2-28-15',
               'C57-10_haloperidol_.25mgkg_ofa60min_041217',
               'C57-12_haloperidol_.25mgkg_ofa60min_041217',
               'C57-1_haloperidol_.25mgkg_ofa60min_041117',
               'C57-2_haloperidol_.25mgkg_ofa60min_041117',
               'C57-4_haloperidol_.25mgkg_ofa60min_041117',
               'C57-6_haloperidol_.25mgkg_ofa60min_041217',
               'C57-7_haloperidol_.25mgkg_ofa60min_041217',
               'C57-8_haloperidol_.25mgkg_ofa60min_041217',
               'C57-10_haloperidol_.5mgkg_ofa60min_041817',
               'C57-11_haloperidol_.5mgkg_ofa60min_041817',
               'C57-12_haloperidol_.5mgkg_ofa60min_041817',
               'C57-1_haloperidol_.5mgkg_ofa60min_041817',
               'C57-2_haloperidol_.5mgkg_ofa60min_041817',
               'C57-3_haloperidol_.5mgkg_ofa60min_041817',
               'C57-4_haloperidol_.5mgkg_ofa60min_041817',
               'C57-5_haloperidol_.5mgkg_ofa60min_041817',
               'C57-6_haloperidol_.5mgkg_ofa60min_041817',
               'C57-7_haloperidol_.5mgkg_ofa60min_041817',
               'C57-8_haloperidol_.5mgkg_ofa60min_041817',
               'C57-9_haloperidol_.5mgkg_ofa60min_041817',
               'C57-10_1mgkg_haloperidol_11-15-16',
               'C57-11_1mgkg_haloperidol_11-15-16',
               'C57-12_1mgkg_haloperidol_11-15-16',
               'C57-1_1mgkg_haloperidol_11-15-16',
               'C57-2_1mgkg_haloperidol_11-15-16',
               'C57-3_1mgkg_haloperidol_11-15-16',
               'C57-4_1mgkg_haloperidol_11-15-16',
               'C57-5_1mgkg_haloperidol_11-15-16',
               'C57-6_1mgkg_haloperidol_11-15-16',
               'C57-7_1mgkg_haloperidol_11-15-16',
               'C57-8_1mgkg_haloperidol_11-15-16',
               'C57-9_1mgkg_haloperidol_11-15-16',
               'C57-10_3mgkg_haloperidol_11-21-16',
               'C57-11_3mgkg_haloperidol_11-21-16',
               'C57-12_3mgkg_haloperidol_11-21-16',
               'C57-1_3mgkg_haloperidol_11-21-16',
               'C57-2_3mgkg_haloperidol_11-21-16',
               'C57-3_3mgkg_haloperidol_11-21-16',
               'C57-4_3mgkg_haloperidol_11-21-16',
               'C57-5_3mgkg_haloperidol_11-21-16',
               'C57-6_3mgkg_haloperidol_11-21-16',
               'C57-7_3mgkg_haloperidol_11-21-16',
               'C57-8_3mgkg_haloperidol_11-21-16',
               'C57-9_3mgkg_haloperidol_11-21-16',
               'C57-10_6mgkg_haloperidol_2-24-15',
               'C57-11_6mgkg_haloperidol_2-24-15',
               'C57-12_6mgkg_haloperidol_2-24-15',
               'C57-1_6mgkg_haloperidol_2-24-15',
               'C57-2_6mgkg_haloperidol_2-24-15',
               'C57-3_6mgkg_haloperidol_2-24-15',
               'C57-4_6mgkg_haloperidol_2-24-15',
               'C57-5_6mgkg_haloperidol_2-24-15',
               'C57-6_6mgkg_haloperidol_2-24-15',
               'C57-7_6mgkg_haloperidol_2-24-15',
               'C57-8_6mgkg_haloperidol_2-24-15',
               'C57-9_6mgkg_haloperidol_2-24-15',

In [4]:
drug_order = [(x if x!="control" else "VEH") for x in fingerprint_labels["unique_drug"]]  # update to new schema
with open(data_output_dir / "drug_order.txt", mode="w") as f:
    f.writelines([s + "\n" for s in drug_order])

In [5]:
index_levels = ["drug_class", "drug", "highorlow", "mouse_names"]
index = list(zip(*[fingerprint_labels[x] for x in index_levels]))

scalars_df = pd.DataFrame(data=fingerprints["scalars"], index=index)
scalars_df.index = pd.MultiIndex.from_tuples(scalars_df.index, names=index_levels)

moseq_df = pd.DataFrame(data=fingerprints["moseq"], index=index)
moseq_df.index = pd.MultiIndex.from_tuples(moseq_df.index, names=index_levels)

moseq_df

                                                                         0   \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000000
                                C57-11_.1mgkg_alprazolam_11-22-16  0.000000
                                C57-12_.1mgkg_alprazolam_11-22-16  0.000000
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000000
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000000
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.000250
                                C57-7_saline_ofa60min_110216       0.000000
                                C57-8_saline_ofa60min_110216       0.000056
                                C57-9_saline_ofa60min_110216       0.000000
                                C57-10_saline_ofa60min_110316      0.000000

                                                                         1   \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000056
                                C57-11_.1mgkg_alprazolam_11-22-16  0.000000
                                C57-12_.1mgkg_alprazolam_11-22-16  0.000111
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000000
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000000
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.000000
                                C57-7_saline_ofa60min_110216       0.000000
                                C57-8_saline_ofa60min_110216       0.000111
                                C57-9_saline_ofa60min_110216       0.000000
                                C57-10_saline_ofa60min_110316      0.000000

                                                                         2   \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000194
                                C57-11_.1mgkg_alprazolam_11-22-16  0.000722
                                C57-12_.1mgkg_alprazolam_11-22-16  0.000722
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000528
                                C57-2_.1mgkg_alprazolam_11-22-16   0.002028
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.001361
                                C57-7_saline_ofa60min_110216       0.000333
                                C57-8_saline_ofa60min_110216       0.000278
                                C57-9_saline_ofa60min_110216       0.000000
                                C57-10_saline_ofa60min_110316      0.000000

                                                                         3   \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000000
                                C57-11_.1mgkg_alprazolam_11-22-16  0.000056
                                C57-12_.1mgkg_alprazolam_11-22-16  0.000472
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000000
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000000
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.000000
                                C57-7_saline_ofa60min_110216       0.000000
                                C57-8_saline_ofa60min_110216       0.000056
                                C57-9_saline_ofa60min_110216       0.000000
                                C57-10_saline_ofa60min_110316      0.000000

                                                                         4   \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.019196
                                C57-11_.1mgkg_alprazolam_11-22-16  0.009695
                                C57-12_.1mgkg_alprazolam_11-22-16  0.030947
                                C57-1_.1mgkg_alprazolam_11-22-16   0.007445
                                C57-2_.1mgkg_alprazolam_11-22-16   0.002111
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.023057
                                C57-7_saline_ofa60min_110216       0.019641
                                C57-8_saline_ofa60min_110216       0.005834
                                C57-9_saline_ofa60min_110216       0.065255
                                C57-10_saline_ofa60min_110316      0.047115

                                                                         5   \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.027252
                                C57-11_.1mgkg_alprazolam_11-22-16  0.035253
                                C57-12_.1mgkg_alprazolam_11-22-16  0.026724
                                C57-1_.1mgkg_alprazolam_11-22-16   0.014668
                                C57-2_.1mgkg_alprazolam_11-22-16   0.032503
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.023002
                                C57-7_saline_ofa60min_110216       0.023030
                                C57-8_saline_ofa60min_110216       0.025224
                                C57-9_saline_ofa60min_110216       0.023030
                                C57-10_saline_ofa60min_110316      0.014557

                                                                         6   \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.001639
                                C57-11_.1mgkg_alprazolam_11-22-16  0.005584
                                C57-12_.1mgkg_alprazolam_11-22-16  0.003473
                                C57-1_.1mgkg_alprazolam_11-22-16   0.002834
                                C57-2_.1mgkg_alprazolam_11-22-16   0.001556
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.003861
                                C57-7_saline_ofa60min_110216       0.004667
                                C57-8_saline_ofa60min_110216       0.002528
                                C57-9_saline_ofa60min_110216       0.002584
                                C57-10_saline_ofa60min_110316      0.001445

                                                                         7   \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.006112
                                C57-11_.1mgkg_alprazolam_11-22-16  0.005612
                                C57-12_.1mgkg_alprazolam_11-22-16  0.007667
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000000
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000389
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.018446
                                C57-7_saline_ofa60min_110216       0.009251
                                C57-8_saline_ofa60min_110216       0.006973
                                C57-9_saline_ofa60min_110216       0.002472
                                C57-10_saline_ofa60min_110316      0.002000

                                                                         8   \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000194
                                C57-11_.1mgkg_alprazolam_11-22-16  0.000361
                                C57-12_.1mgkg_alprazolam_11-22-16  0.000361
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000000
                                C57-2_.1mgkg_alprazolam_11-22-16   0.001195
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.000472
                                C57-7_saline_ofa60min_110216       0.001195
                                C57-8_saline_ofa60min_110216       0.000417
                                C57-9_saline_ofa60min_110216       0.000056
                                C57-10_saline_ofa60min_110316      0.000306

                                                                         9   \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.023113
                                C57-11_.1mgkg_alprazolam_11-22-16  0.034281
                                C57-12_.1mgkg_alprazolam_11-22-16  0.019029
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000750
                                C57-2_.1mgkg_alprazolam_11-22-16   0.003250
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.032475
                                C57-7_saline_ofa60min_110216       0.034170
                                C57-8_saline_ofa60min_110216       0.055782
                                C57-9_saline_ofa60min_110216       0.022169
                                C57-10_saline_ofa60min_110316      0.010501

                                                                   ...  \
drug_class drug       highorlow mouse_names                        ...
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  ...
                                C57-11_.1mgkg_alprazolam_11-22-16  ...
                                C57-12_.1mgkg_alprazolam_11-22-16  ...
                                C57-1_.1mgkg_alprazolam_11-22-16   ...
                                C57-2_.1mgkg_alprazolam_11-22-16   ...
...                                                                ...
control    control    Low       C57-6_saline_ofa60min_110216       ...
                                C57-7_saline_ofa60min_110216       ...
                                C57-8_saline_ofa60min_110216       ...
                                C57-9_saline_ofa60min_110216       ...
                                C57-10_saline_ofa60min_110316      ...

                                                                         80  \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.016890
                                C57-11_.1mgkg_alprazolam_11-22-16  0.003556
                                C57-12_.1mgkg_alprazolam_11-22-16  0.011973
                                C57-1_.1mgkg_alprazolam_11-22-16   0.014473
                                C57-2_.1mgkg_alprazolam_11-22-16   0.011195
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.037309
                                C57-7_saline_ofa60min_110216       0.007778
                                C57-8_saline_ofa60min_110216       0.009612
                                C57-9_saline_ofa60min_110216       0.006112
                                C57-10_saline_ofa60min_110316      0.033031

                                                                         81  \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.004195
                                C57-11_.1mgkg_alprazolam_11-22-16  0.002611
                                C57-12_.1mgkg_alprazolam_11-22-16  0.002500
                                C57-1_.1mgkg_alprazolam_11-22-16   0.006112
                                C57-2_.1mgkg_alprazolam_11-22-16   0.015140
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.009890
                                C57-7_saline_ofa60min_110216       0.004473
                                C57-8_saline_ofa60min_110216       0.006501
                                C57-9_saline_ofa60min_110216       0.009751
                                C57-10_saline_ofa60min_110316      0.019224

                                                                         82  \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.003723
                                C57-11_.1mgkg_alprazolam_11-22-16  0.007390
                                C57-12_.1mgkg_alprazolam_11-22-16  0.003111
                                C57-1_.1mgkg_alprazolam_11-22-16   0.001111
                                C57-2_.1mgkg_alprazolam_11-22-16   0.005334
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.008612
                                C57-7_saline_ofa60min_110216       0.008390
                                C57-8_saline_ofa60min_110216       0.006028
                                C57-9_saline_ofa60min_110216       0.005028
                                C57-10_saline_ofa60min_110316      0.005917

                                                                         83  \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.012529
                                C57-11_.1mgkg_alprazolam_11-22-16  0.009529
                                C57-12_.1mgkg_alprazolam_11-22-16  0.009112
                                C57-1_.1mgkg_alprazolam_11-22-16   0.041976
                                C57-2_.1mgkg_alprazolam_11-22-16   0.018224
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.008362
                                C57-7_saline_ofa60min_110216       0.012445
                                C57-8_saline_ofa60min_110216       0.014446
                                C57-9_saline_ofa60min_110216       0.013251
                                C57-10_saline_ofa60min_110316      0.012918

                                                                         84  \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000667
                                C57-11_.1mgkg_alprazolam_11-22-16  0.001195
                                C57-12_.1mgkg_alprazolam_11-22-16  0.000639
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000139
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000695
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.001000
                                C57-7_saline_ofa60min_110216       0.000111
                                C57-8_saline_ofa60min_110216       0.001083
                                C57-9_saline_ofa60min_110216       0.001889
                                C57-10_saline_ofa60min_110316      0.001333

                                                                         85  \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.009001
                                C57-11_.1mgkg_alprazolam_11-22-16  0.003222
                                C57-12_.1mgkg_alprazolam_11-22-16  0.006639
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000000
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000167
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.001056
                                C57-7_saline_ofa60min_110216       0.004639
                                C57-8_saline_ofa60min_110216       0.001222
                                C57-9_saline_ofa60min_110216       0.001250
                                C57-10_saline_ofa60min_110316      0.001083

                                                                         86  \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000722
                                C57-11_.1mgkg_alprazolam_11-22-16  0.000056
                                C57-12_.1mgkg_alprazolam_11-22-16  0.000306
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000111
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000639
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.000250
                                C57-7_saline_ofa60min_110216       0.000000
                                C57-8_saline_ofa60min_110216       0.000139
                                C57-9_saline_ofa60min_110216       0.000250
                                C57-10_saline_ofa60min_110316      0.000056

                                                                         87  \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.004084
                                C57-11_.1mgkg_alprazolam_11-22-16  0.006223
                                C57-12_.1mgkg_alprazolam_11-22-16  0.005250
                                C57-1_.1mgkg_alprazolam_11-22-16   0.011390
                                C57-2_.1mgkg_alprazolam_11-22-16   0.021946
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.018890
                                C57-7_saline_ofa60min_110216       0.027169
                                C57-8_saline_ofa60min_110216       0.007806
                                C57-9_saline_ofa60min_110216       0.020363
                                C57-10_saline_ofa60min_110316      0.025669

                                                                         88  \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.006251
                                C57-11_.1mgkg_alprazolam_11-22-16  0.003000
                                C57-12_.1mgkg_alprazolam_11-22-16  0.003834
                                C57-1_.1mgkg_alprazolam_11-22-16   0.001333
                                C57-2_.1mgkg_alprazolam_11-22-16   0.003778
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.002084
                                C57-7_saline_ofa60min_110216       0.005917
                                C57-8_saline_ofa60min_110216       0.003445
                                C57-9_saline_ofa60min_110216       0.002584
                                C57-10_saline_ofa60min_110316      0.005695

                                                                         89
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.003861
                                C57-11_.1mgkg_alprazolam_11-22-16  0.007084
                                C57-12_.1mgkg_alprazolam_11-22-16  0.007112
                                C57-1_.1mgkg_alprazolam_11-22-16   0.005723
                                C57-2_.1mgkg_alprazolam_11-22-16   0.009640
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.011473
                                C57-7_saline_ofa60min_110216       0.006889
                                C57-8_saline_ofa60min_110216       0.006001

In [6]:
with open(data_root_dir / "dataset.pkl", "rb") as f:
    dataset = pickle.load(f, encoding='latin1')

def _dict_to_df(data_dict, index_key="mouse_img_idx", ignore_keys=("good_idx", "roi", "data", "pca_components")):
    return pd.DataFrame({col: data_dict[col].flatten() for col in data_dict.keys() if col not in (index_key, *ignore_keys)})

full_df = pd.concat({k: _dict_to_df(v) for k,v in dataset.items()}, names=["mouse_names", "frame_idx"])
full_df["velocity"] = full_df["velocity"].abs()  # why do negative velocities exist...?
full_df

                                                angle  dist_to_center  area  \
mouse_names                       frame_idx
C57-10_.1mgkg_alprazolam_11-22-16 0          2.008199        0.964150   472
                                  1          1.999063        0.962104   478
                                  2          2.191172        0.962236   446
                                  3          2.104875        0.962133   442
                                  4          2.239870        0.957401   442
...                                               ...             ...   ...
C57-10_saline_ofa60min_110316     35995      4.293032        0.292547   644
                                  35996      4.302509        0.271447   628
                                  35997      4.286060        0.252450   652
                                  35998      4.327171        0.232664   620
                                  35999      4.390185        0.214797   582

                                             centroid_y     height      width  \
mouse_names                       frame_idx
C57-10_.1mgkg_alprazolam_11-22-16 0           64.983174  31.739683  32.518192
                                  1           65.008404  31.739002  32.263863
                                  2           64.848374  28.730247  30.729359
                                  3           64.814363  28.657526  30.850973
                                  4           65.026599  28.616653  30.734591
...                                                 ...        ...        ...
C57-10_saline_ofa60min_110316     35995      130.260475  33.072868  29.746565
                                  35996      128.404205  33.055080  29.199207
                                  35997      126.521764  32.038303  28.472429
                                  35998      124.873223  30.456245  27.747793
                                  35999      122.814313  29.900949  27.583782

                                                length  velocity  centroid_x
mouse_names                       frame_idx
C57-10_.1mgkg_alprazolam_11-22-16 0          46.020905  0.000000   14.643716
                                  1          45.882473  0.073483   14.610511
                                  2          46.310711  0.009120   14.378685
                                  3          46.599613  0.101638   14.221344
                                  4          46.743885  0.450663   14.126457
...                                                ...       ...         ...
C57-10_saline_ofa60min_110316     35995      65.804985  3.545061  104.034518
                                  35996      64.616402  3.807600  103.529405
                                  35997      67.288696  3.928421  102.924209
                                  35998      66.837486  3.666865  102.110653
                                  35999      61.092407  4.731890  100.806448

[18036000 rows x 9 columns]

In [7]:
bin_dict = {
    "dist_to_center": np.linspace(0, 1, 90),
    "height": np.linspace(0, 60, 45),
    "velocity": np.linspace(0, 20, 90),
    "length": np.linspace(20, 100, 45)
}

def _dataset_to_scalars(dataset_df, density=False):
    if not density:
        hist_func = lambda x: pd.Series(np.concatenate([np.histogram(x[c], bins=bin_dict[c], density=False)[0] for c in bin_dict.keys()]))
    else:
        hist_func = lambda x: pd.Series(np.concatenate([np.histogram(x[c], bins=bin_dict[c], density=True)[0]/(1/np.diff(bin_dict[c])[1]) for c in bin_dict.keys()]))
    return dataset_df.groupby("mouse_names").apply(hist_func)

reproduced_scalars_df = _dataset_to_scalars(full_df, density=False)
_idx = pd.DataFrame(index, columns=index_levels).set_index("mouse_names")
reproduced_scalars_df = reproduced_scalars_df.join(_idx).reset_index().set_index(index_levels).reindex(index=scalars_df.index)
reproduced_scalars_df.equals(scalars_df)

True

In [8]:
density_scalars_df = _dataset_to_scalars(full_df, density=True)
_idx = pd.DataFrame(index, columns=index_levels).set_index("mouse_names")
density_scalars_df = density_scalars_df.join(_idx).reset_index().set_index(index_levels).reindex(index=scalars_df.index)
print(density_scalars_df.equals(scalars_df))
density_scalars_df

False

                                                                        0    \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000000
                                C57-11_.1mgkg_alprazolam_11-22-16  0.000000
                                C57-12_.1mgkg_alprazolam_11-22-16  0.000278
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000028
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000194
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.000111
                                C57-7_saline_ofa60min_110216       0.000167
                                C57-8_saline_ofa60min_110216       0.000028
                                C57-9_saline_ofa60min_110216       0.000139
                                C57-10_saline_ofa60min_110316      0.000112

                                                                        1    \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000028
                                C57-11_.1mgkg_alprazolam_11-22-16  0.000361
                                C57-12_.1mgkg_alprazolam_11-22-16  0.000222
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000251
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000389
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.000250
                                C57-7_saline_ofa60min_110216       0.000334
                                C57-8_saline_ofa60min_110216       0.000056
                                C57-9_saline_ofa60min_110216       0.000445
                                C57-10_saline_ofa60min_110316      0.000363

                                                                        2    \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000083
                                C57-11_.1mgkg_alprazolam_11-22-16  0.000250
                                C57-12_.1mgkg_alprazolam_11-22-16  0.000500
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000363
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000667
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.000722
                                C57-7_saline_ofa60min_110216       0.000584
                                C57-8_saline_ofa60min_110216       0.000111
                                C57-9_saline_ofa60min_110216       0.000556
                                C57-10_saline_ofa60min_110316      0.000586

                                                                        3    \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000111
                                C57-11_.1mgkg_alprazolam_11-22-16  0.000833
                                C57-12_.1mgkg_alprazolam_11-22-16  0.000417
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000307
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000222
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.000361
                                C57-7_saline_ofa60min_110216       0.001306
                                C57-8_saline_ofa60min_110216       0.000194
                                C57-9_saline_ofa60min_110216       0.000556
                                C57-10_saline_ofa60min_110316      0.003181

                                                                        4    \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000028
                                C57-11_.1mgkg_alprazolam_11-22-16  0.001611
                                C57-12_.1mgkg_alprazolam_11-22-16  0.000695
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000558
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000333
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.000194
                                C57-7_saline_ofa60min_110216       0.001529
                                C57-8_saline_ofa60min_110216       0.000222
                                C57-9_saline_ofa60min_110216       0.000528
                                C57-10_saline_ofa60min_110316      0.001283

                                                                        5    \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000167
                                C57-11_.1mgkg_alprazolam_11-22-16  0.001583
                                C57-12_.1mgkg_alprazolam_11-22-16  0.001473
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000447
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000695
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.000250
                                C57-7_saline_ofa60min_110216       0.002140
                                C57-8_saline_ofa60min_110216       0.000861
                                C57-9_saline_ofa60min_110216       0.000778
                                C57-10_saline_ofa60min_110316      0.000558

                                                                        6    \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000139
                                C57-11_.1mgkg_alprazolam_11-22-16  0.000972
                                C57-12_.1mgkg_alprazolam_11-22-16  0.001585
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000642
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000306
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.000472
                                C57-7_saline_ofa60min_110216       0.003613
                                C57-8_saline_ofa60min_110216       0.000556
                                C57-9_saline_ofa60min_110216       0.001084
                                C57-10_saline_ofa60min_110316      0.000614

                                                                        7    \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000195
                                C57-11_.1mgkg_alprazolam_11-22-16  0.000778
                                C57-12_.1mgkg_alprazolam_11-22-16  0.002530
                                C57-1_.1mgkg_alprazolam_11-22-16   0.001228
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000778
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.000861
                                C57-7_saline_ofa60min_110216       0.003335
                                C57-8_saline_ofa60min_110216       0.000250
                                C57-9_saline_ofa60min_110216       0.000889
                                C57-10_saline_ofa60min_110316      0.000697

                                                                        8    \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000557
                                C57-11_.1mgkg_alprazolam_11-22-16  0.001222
                                C57-12_.1mgkg_alprazolam_11-22-16  0.002169
                                C57-1_.1mgkg_alprazolam_11-22-16   0.002205
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000778
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.001000
                                C57-7_saline_ofa60min_110216       0.003446
                                C57-8_saline_ofa60min_110216       0.000472
                                C57-9_saline_ofa60min_110216       0.001695
                                C57-10_saline_ofa60min_110316      0.000809

                                                                        9    \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000612
                                C57-11_.1mgkg_alprazolam_11-22-16  0.001417
                                C57-12_.1mgkg_alprazolam_11-22-16  0.002085
                                C57-1_.1mgkg_alprazolam_11-22-16   0.002484
                                C57-2_.1mgkg_alprazolam_11-22-16   0.001000
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.001250
                                C57-7_saline_ofa60min_110216       0.002696
                                C57-8_saline_ofa60min_110216       0.000611
                                C57-9_saline_ofa60min_110216       0.002028
                                C57-10_saline_ofa60min_110316      0.001562

                                                                   ...  \
drug_class drug       highorlow mouse_names                        ...
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  ...
                                C57-11_.1mgkg_alprazolam_11-22-16  ...
                                C57-12_.1mgkg_alprazolam_11-22-16  ...
                                C57-1_.1mgkg_alprazolam_11-22-16   ...
                                C57-2_.1mgkg_alprazolam_11-22-16   ...
...                                                                ...
control    control    Low       C57-6_saline_ofa60min_110216       ...
                                C57-7_saline_ofa60min_110216       ...
                                C57-8_saline_ofa60min_110216       ...
                                C57-9_saline_ofa60min_110216       ...
                                C57-10_saline_ofa60min_110316      ...

                                                                        256  \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.006468
                                C57-11_.1mgkg_alprazolam_11-22-16  0.007112
                                C57-12_.1mgkg_alprazolam_11-22-16  0.004880
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000141
                                C57-2_.1mgkg_alprazolam_11-22-16   0.001809
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.008642
                                C57-7_saline_ofa60min_110216       0.010903
                                C57-8_saline_ofa60min_110216       0.011252
                                C57-9_saline_ofa60min_110216       0.004202
                                C57-10_saline_ofa60min_110316      0.003049

                                                                        257  \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.005213
                                C57-11_.1mgkg_alprazolam_11-22-16  0.004945
                                C57-12_.1mgkg_alprazolam_11-22-16  0.003514
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000056
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000835
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.004363
                                C57-7_saline_ofa60min_110216       0.008316
                                C57-8_saline_ofa60min_110216       0.006140
                                C57-9_saline_ofa60min_110216       0.002087
                                C57-10_saline_ofa60min_110316      0.001986

                                                                        258  \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.004461
                                C57-11_.1mgkg_alprazolam_11-22-16  0.003028
                                C57-12_.1mgkg_alprazolam_11-22-16  0.002538
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000028
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000306
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.003029
                                C57-7_saline_ofa60min_110216       0.006202
                                C57-8_saline_ofa60min_110216       0.003584
                                C57-9_saline_ofa60min_110216       0.001030
                                C57-10_saline_ofa60min_110316      0.001035

                                                                        259  \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.003429
                                C57-11_.1mgkg_alprazolam_11-22-16  0.002306
                                C57-12_.1mgkg_alprazolam_11-22-16  0.001589
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000000
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000223
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.001612
                                C57-7_saline_ofa60min_110216       0.004311
                                C57-8_saline_ofa60min_110216       0.001750
                                C57-9_saline_ofa60min_110216       0.000974
                                C57-10_saline_ofa60min_110316      0.000531

                                                                        260  \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.001812
                                C57-11_.1mgkg_alprazolam_11-22-16  0.001167
                                C57-12_.1mgkg_alprazolam_11-22-16  0.001283
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000000
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000111
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.000556
                                C57-7_saline_ofa60min_110216       0.002893
                                C57-8_saline_ofa60min_110216       0.000917
                                C57-9_saline_ofa60min_110216       0.000334
                                C57-10_saline_ofa60min_110316      0.000252

                                                                        261  \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.001227
                                C57-11_.1mgkg_alprazolam_11-22-16  0.000806
                                C57-12_.1mgkg_alprazolam_11-22-16  0.000809
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000000
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000139
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.000472
                                C57-7_saline_ofa60min_110216       0.001279
                                C57-8_saline_ofa60min_110216       0.000194
                                C57-9_saline_ofa60min_110216       0.000056
                                C57-10_saline_ofa60min_110316      0.000168

                                                                        262  \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000781
                                C57-11_.1mgkg_alprazolam_11-22-16  0.000528
                                C57-12_.1mgkg_alprazolam_11-22-16  0.000251
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000000
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000000
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.000389
                                C57-7_saline_ofa60min_110216       0.000973
                                C57-8_saline_ofa60min_110216       0.000167
                                C57-9_saline_ofa60min_110216       0.000111
                                C57-10_saline_ofa60min_110316      0.000140

                                                                        263  \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000000
                                C57-11_.1mgkg_alprazolam_11-22-16  0.000306
                                C57-12_.1mgkg_alprazolam_11-22-16  0.000223
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000000
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000000
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.000222
                                C57-7_saline_ofa60min_110216       0.000473
                                C57-8_saline_ofa60min_110216       0.000028
                                C57-9_saline_ofa60min_110216       0.000056
                                C57-10_saline_ofa60min_110316      0.000000

                                                                        264  \
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000000
                                C57-11_.1mgkg_alprazolam_11-22-16  0.000111
                                C57-12_.1mgkg_alprazolam_11-22-16  0.000112
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000000
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000000
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.000056
                                C57-7_saline_ofa60min_110216       0.000334
                                C57-8_saline_ofa60min_110216       0.000056
                                C57-9_saline_ofa60min_110216       0.000000
                                C57-10_saline_ofa60min_110316      0.000056

                                                                        265
drug_class drug       highorlow mouse_names
benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  0.000000
                                C57-11_.1mgkg_alprazolam_11-22-16  0.000167
                                C57-12_.1mgkg_alprazolam_11-22-16  0.000056
                                C57-1_.1mgkg_alprazolam_11-22-16   0.000000
                                C57-2_.1mgkg_alprazolam_11-22-16   0.000000
...                                                                     ...
control    control    Low       C57-6_saline_ofa60min_110216       0.000028
                                C57-7_saline_ofa60min_110216       0.000362
                                C57-8_saline_ofa60min_110216       0.000028

In [9]:
def preprocess_features(input_feature_df, n_components=0.95, rescale=True, pca=True):
    feature_array = input_feature_df.copy().values
    if rescale:
        feature_array = StandardScaler().fit_transform(feature_array)
    if pca:
        feature_array = PCA(n_components=n_components).fit_transform(feature_array)
    return pd.DataFrame(data=feature_array, index=input_feature_df.index)

pca_scalars_df = preprocess_features(density_scalars_df, rescale=False, pca=True)
pca_moseq_df = preprocess_features(moseq_df, rescale=False, pca=True)

rescaled_pca_scalars_df = preprocess_features(density_scalars_df, rescale=True, pca=True)
rescaled_pca_moseq_df = preprocess_features(moseq_df, rescale=True, pca=True)

In [10]:
scalars_df_dict = dict(
    raw=scalars_df,
    density=density_scalars_df,
    pca=pca_scalars_df,
    rescaled_pca=rescaled_pca_scalars_df
)

approach_scalars_df = pd.concat(scalars_df_dict, names=["approach"])

moseq_df_dict = dict(
    raw=moseq_df,
    density=moseq_df,
    pca=pca_moseq_df,
    rescaled_pca=rescaled_pca_moseq_df
)

approach_moseq_df = pd.concat(moseq_df_dict, names=["approach"])

save_object(approach_scalars_df, data_output_dir / "approach_scalars_df.pkl", overwrite=True)
save_object(approach_moseq_df, data_output_dir / "approach_moseq_df.pkl", overwrite=True)
approach_scalars_df

                                                                                      0    \
approach     drug_class drug       highorlow mouse_names
raw          benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16   0.000000
                                             C57-11_.1mgkg_alprazolam_11-22-16   0.000000
                                             C57-12_.1mgkg_alprazolam_11-22-16  10.000000
                                             C57-1_.1mgkg_alprazolam_11-22-16    1.000000
                                             C57-2_.1mgkg_alprazolam_11-22-16    7.000000
...                                                                                   ...
rescaled_pca control    control    Low       C57-6_saline_ofa60min_110216       -1.327872
                                             C57-7_saline_ofa60min_110216       -1.657833
                                             C57-8_saline_ofa60min_110216       -0.015075
                                             C57-9_saline_ofa60min_110216       -2.259192
                                             C57-10_saline_ofa60min_110316      -1.773798

                                                                                      1    \
approach     drug_class drug       highorlow mouse_names
raw          benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16   1.000000
                                             C57-11_.1mgkg_alprazolam_11-22-16  13.000000
                                             C57-12_.1mgkg_alprazolam_11-22-16   8.000000
                                             C57-1_.1mgkg_alprazolam_11-22-16    9.000000
                                             C57-2_.1mgkg_alprazolam_11-22-16   14.000000
...                                                                                   ...
rescaled_pca control    control    Low       C57-6_saline_ofa60min_110216        7.826344
                                             C57-7_saline_ofa60min_110216        7.694171
                                             C57-8_saline_ofa60min_110216        5.643562
                                             C57-9_saline_ofa60min_110216        6.239537
                                             C57-10_saline_ofa60min_110316      10.862907

                                                                                      2    \
approach     drug_class drug       highorlow mouse_names
raw          benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16   3.000000
                                             C57-11_.1mgkg_alprazolam_11-22-16   9.000000
                                             C57-12_.1mgkg_alprazolam_11-22-16  18.000000
                                             C57-1_.1mgkg_alprazolam_11-22-16   13.000000
                                             C57-2_.1mgkg_alprazolam_11-22-16   24.000000
...                                                                                   ...
rescaled_pca control    control    Low       C57-6_saline_ofa60min_110216       -3.228296
                                             C57-7_saline_ofa60min_110216       -2.075255
                                             C57-8_saline_ofa60min_110216       -1.473362
                                             C57-9_saline_ofa60min_110216       -1.355260
                                             C57-10_saline_ofa60min_110316      -7.909997

                                                                                      3    \
approach     drug_class drug       highorlow mouse_names
raw          benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16   4.000000
                                             C57-11_.1mgkg_alprazolam_11-22-16  30.000000
                                             C57-12_.1mgkg_alprazolam_11-22-16  15.000000
                                             C57-1_.1mgkg_alprazolam_11-22-16   11.000000
                                             C57-2_.1mgkg_alprazolam_11-22-16    8.000000
...                                                                                   ...
rescaled_pca control    control    Low       C57-6_saline_ofa60min_110216       -2.620568
                                             C57-7_saline_ofa60min_110216       -2.668443
                                             C57-8_saline_ofa60min_110216       -3.034562
                                             C57-9_saline_ofa60min_110216        0.687645
                                             C57-10_saline_ofa60min_110316       0.391372

                                                                                      4    \
approach     drug_class drug       highorlow mouse_names
raw          benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16   1.000000
                                             C57-11_.1mgkg_alprazolam_11-22-16  58.000000
                                             C57-12_.1mgkg_alprazolam_11-22-16  25.000000
                                             C57-1_.1mgkg_alprazolam_11-22-16   20.000000
                                             C57-2_.1mgkg_alprazolam_11-22-16   12.000000
...                                                                                   ...
rescaled_pca control    control    Low       C57-6_saline_ofa60min_110216       -1.974463
                                             C57-7_saline_ofa60min_110216       -0.278256
                                             C57-8_saline_ofa60min_110216       -0.577113
                                             C57-9_saline_ofa60min_110216       -1.059507
                                             C57-10_saline_ofa60min_110316      -4.219813

                                                                                      5    \
approach     drug_class drug       highorlow mouse_names
raw          benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16   6.000000
                                             C57-11_.1mgkg_alprazolam_11-22-16  57.000000
                                             C57-12_.1mgkg_alprazolam_11-22-16  53.000000
                                             C57-1_.1mgkg_alprazolam_11-22-16   16.000000
                                             C57-2_.1mgkg_alprazolam_11-22-16   25.000000
...                                                                                   ...
rescaled_pca control    control    Low       C57-6_saline_ofa60min_110216        1.080542
                                             C57-7_saline_ofa60min_110216        0.748838
                                             C57-8_saline_ofa60min_110216        0.768594
                                             C57-9_saline_ofa60min_110216        1.280405
                                             C57-10_saline_ofa60min_110316      -0.579703

                                                                                      6    \
approach     drug_class drug       highorlow mouse_names
raw          benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16   5.000000
                                             C57-11_.1mgkg_alprazolam_11-22-16  35.000000
                                             C57-12_.1mgkg_alprazolam_11-22-16  57.000000
                                             C57-1_.1mgkg_alprazolam_11-22-16   23.000000
                                             C57-2_.1mgkg_alprazolam_11-22-16   11.000000
...                                                                                   ...
rescaled_pca control    control    Low       C57-6_saline_ofa60min_110216        0.883674
                                             C57-7_saline_ofa60min_110216        1.024589
                                             C57-8_saline_ofa60min_110216       -0.867303
                                             C57-9_saline_ofa60min_110216       -1.061537
                                             C57-10_saline_ofa60min_110316       2.823010

                                                                                      7    \
approach     drug_class drug       highorlow mouse_names
raw          benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16   7.000000
                                             C57-11_.1mgkg_alprazolam_11-22-16  28.000000
                                             C57-12_.1mgkg_alprazolam_11-22-16  91.000000
                                             C57-1_.1mgkg_alprazolam_11-22-16   44.000000
                                             C57-2_.1mgkg_alprazolam_11-22-16   28.000000
...                                                                                   ...
rescaled_pca control    control    Low       C57-6_saline_ofa60min_110216       -0.616965
                                             C57-7_saline_ofa60min_110216       -0.395449
                                             C57-8_saline_ofa60min_110216        0.103699
                                             C57-9_saline_ofa60min_110216       -0.086761
                                             C57-10_saline_ofa60min_110316      -1.032543

                                                                                      8    \
approach     drug_class drug       highorlow mouse_names
raw          benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  20.000000
                                             C57-11_.1mgkg_alprazolam_11-22-16  44.000000
                                             C57-12_.1mgkg_alprazolam_11-22-16  78.000000
                                             C57-1_.1mgkg_alprazolam_11-22-16   79.000000
                                             C57-2_.1mgkg_alprazolam_11-22-16   28.000000
...                                                                                   ...
rescaled_pca control    control    Low       C57-6_saline_ofa60min_110216        3.814091
                                             C57-7_saline_ofa60min_110216       -1.022801
                                             C57-8_saline_ofa60min_110216        4.283315
                                             C57-9_saline_ofa60min_110216        0.721877
                                             C57-10_saline_ofa60min_110316      -0.999102

                                                                                      9    \
approach     drug_class drug       highorlow mouse_names
raw          benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  22.000000
                                             C57-11_.1mgkg_alprazolam_11-22-16  51.000000
                                             C57-12_.1mgkg_alprazolam_11-22-16  75.000000
                                             C57-1_.1mgkg_alprazolam_11-22-16   89.000000
                                             C57-2_.1mgkg_alprazolam_11-22-16   36.000000
...                                                                                   ...
rescaled_pca control    control    Low       C57-6_saline_ofa60min_110216       -2.573123
                                             C57-7_saline_ofa60min_110216       -0.930866
                                             C57-8_saline_ofa60min_110216       -2.841430
                                             C57-9_saline_ofa60min_110216       -0.077837
                                             C57-10_saline_ofa60min_110316       2.065069

                                                                                ...  \
approach     drug_class drug       highorlow mouse_names                        ...
raw          benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  ...
                                             C57-11_.1mgkg_alprazolam_11-22-16  ...
                                             C57-12_.1mgkg_alprazolam_11-22-16  ...
                                             C57-1_.1mgkg_alprazolam_11-22-16   ...
                                             C57-2_.1mgkg_alprazolam_11-22-16   ...
...                                                                             ...
rescaled_pca control    control    Low       C57-6_saline_ofa60min_110216       ...
                                             C57-7_saline_ofa60min_110216       ...
                                             C57-8_saline_ofa60min_110216       ...
                                             C57-9_saline_ofa60min_110216       ...
                                             C57-10_saline_ofa60min_110316      ...

                                                                                  256  \
approach     drug_class drug       highorlow mouse_names
raw          benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  232.0
                                             C57-11_.1mgkg_alprazolam_11-22-16  256.0
                                             C57-12_.1mgkg_alprazolam_11-22-16  175.0
                                             C57-1_.1mgkg_alprazolam_11-22-16     5.0
                                             C57-2_.1mgkg_alprazolam_11-22-16    65.0
...                                                                               ...
rescaled_pca control    control    Low       C57-6_saline_ofa60min_110216         NaN
                                             C57-7_saline_ofa60min_110216         NaN
                                             C57-8_saline_ofa60min_110216         NaN
                                             C57-9_saline_ofa60min_110216         NaN
                                             C57-10_saline_ofa60min_110316        NaN

                                                                                  257  \
approach     drug_class drug       highorlow mouse_names
raw          benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  187.0
                                             C57-11_.1mgkg_alprazolam_11-22-16  178.0
                                             C57-12_.1mgkg_alprazolam_11-22-16  126.0
                                             C57-1_.1mgkg_alprazolam_11-22-16     2.0
                                             C57-2_.1mgkg_alprazolam_11-22-16    30.0
...                                                                               ...
rescaled_pca control    control    Low       C57-6_saline_ofa60min_110216         NaN
                                             C57-7_saline_ofa60min_110216         NaN
                                             C57-8_saline_ofa60min_110216         NaN
                                             C57-9_saline_ofa60min_110216         NaN
                                             C57-10_saline_ofa60min_110316        NaN

                                                                                  258  \
approach     drug_class drug       highorlow mouse_names
raw          benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  160.0
                                             C57-11_.1mgkg_alprazolam_11-22-16  109.0
                                             C57-12_.1mgkg_alprazolam_11-22-16   91.0
                                             C57-1_.1mgkg_alprazolam_11-22-16     1.0
                                             C57-2_.1mgkg_alprazolam_11-22-16    11.0
...                                                                               ...
rescaled_pca control    control    Low       C57-6_saline_ofa60min_110216         NaN
                                             C57-7_saline_ofa60min_110216         NaN
                                             C57-8_saline_ofa60min_110216         NaN
                                             C57-9_saline_ofa60min_110216         NaN
                                             C57-10_saline_ofa60min_110316        NaN

                                                                                  259  \
approach     drug_class drug       highorlow mouse_names
raw          benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  123.0
                                             C57-11_.1mgkg_alprazolam_11-22-16   83.0
                                             C57-12_.1mgkg_alprazolam_11-22-16   57.0
                                             C57-1_.1mgkg_alprazolam_11-22-16     0.0
                                             C57-2_.1mgkg_alprazolam_11-22-16     8.0
...                                                                               ...
rescaled_pca control    control    Low       C57-6_saline_ofa60min_110216         NaN
                                             C57-7_saline_ofa60min_110216         NaN
                                             C57-8_saline_ofa60min_110216         NaN
                                             C57-9_saline_ofa60min_110216         NaN
                                             C57-10_saline_ofa60min_110316        NaN

                                                                                 260  \
approach     drug_class drug       highorlow mouse_names
raw          benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  65.0
                                             C57-11_.1mgkg_alprazolam_11-22-16  42.0
                                             C57-12_.1mgkg_alprazolam_11-22-16  46.0
                                             C57-1_.1mgkg_alprazolam_11-22-16    0.0
                                             C57-2_.1mgkg_alprazolam_11-22-16    4.0
...                                                                              ...
rescaled_pca control    control    Low       C57-6_saline_ofa60min_110216        NaN
                                             C57-7_saline_ofa60min_110216        NaN
                                             C57-8_saline_ofa60min_110216        NaN
                                             C57-9_saline_ofa60min_110216        NaN
                                             C57-10_saline_ofa60min_110316       NaN

                                                                                 261  \
approach     drug_class drug       highorlow mouse_names
raw          benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  44.0
                                             C57-11_.1mgkg_alprazolam_11-22-16  29.0
                                             C57-12_.1mgkg_alprazolam_11-22-16  29.0
                                             C57-1_.1mgkg_alprazolam_11-22-16    0.0
                                             C57-2_.1mgkg_alprazolam_11-22-16    5.0
...                                                                              ...
rescaled_pca control    control    Low       C57-6_saline_ofa60min_110216        NaN
                                             C57-7_saline_ofa60min_110216        NaN
                                             C57-8_saline_ofa60min_110216        NaN
                                             C57-9_saline_ofa60min_110216        NaN
                                             C57-10_saline_ofa60min_110316       NaN

                                                                                 262  \
approach     drug_class drug       highorlow mouse_names
raw          benzo      alprazolam Low       C57-10_.1mgkg_alprazolam_11-22-16  28.0
                                             C57-11_.1mgkg_alprazolam_11-22-16  19.0
                                             C57-12_.1mgkg_alprazolam_11-22-16   9.0
                                             C57-1_.1mgkg_alprazolam_11-22-16    0.0
                                             C57-2_.1mgkg_alprazolam_11-22-16    0.0
...                                                                              ...
rescaled_pca control    control    Low       C57-6_saline_ofa60min_110216        NaN
                                             C57-7_saline_ofa60min_110216        NaN
                                             C57-8_saline_ofa60min_110216        NaN

In [11]:
vector_df = pd.concat({
    "scalars": approach_scalars_df,
    "moseq": approach_moseq_df
}, names=["segmenter"]).sort_index()
vector_df.index.names = ["segmenter", "approach", "drug_class", "treatment", "uniform_dosage_term", "mouse_names"]
vector_df.columns.name = "behavior_name"
_idx = vector_df.index.to_frame(index=False)
_idx["uniform_dosage_term"] = _idx["uniform_dosage_term"].str.lower()
_idx["treatment_mouse_id"] =  _idx["mouse_names"].str.extract(r"^.+?\-(\d+)\_").astype(int)
_idx["phase"] = "Solitary"

_control_idx = _idx[_idx["treatment"].eq("control")]
_idx.loc[_control_idx.index, "treatment_mouse_id"] = _control_idx.groupby(["approach", "segmenter", "treatment", "uniform_dosage_term"]).apply(lambda x: pd.Series(range(len(x)), dtype=int), include_groups=False).stack().values
_idx.loc[_control_idx.index, "treatment"] = "VEH"
_idx.loc[_control_idx.index, "uniform_dosage_term"] = "medium"

vector_df.index = pd.MultiIndex.from_frame(_idx[["approach", "segmenter", "phase", "treatment", "uniform_dosage_term", "treatment_mouse_id"]])

save_object(vector_df.fillna(0), data_output_dir / "approach_vector_df.pkl", overwrite=True)
vector_df

behavior_name                                                                          0    \
approach     segmenter phase    treatment uniform_dosage_term treatment_mouse_id
density      moseq     Solitary bupropion high                10                  0.000000
                                                              11                  0.000000
                                                              12                  0.000000
                                                              1                   0.000000
                                                              2                   0.000000
...                                                                                    ...
rescaled_pca scalars   Solitary modafinil low                 5                  -4.699806
                                                              6                   5.418398
                                                              7                   3.897948
                                                              8                  -4.736659
                                                              9                  -2.074701

behavior_name                                                                          1    \
approach     segmenter phase    treatment uniform_dosage_term treatment_mouse_id
density      moseq     Solitary bupropion high                10                  0.000000
                                                              11                  0.000000
                                                              12                  0.000000
                                                              1                   0.000000
                                                              2                   0.000000
...                                                                                    ...
rescaled_pca scalars   Solitary modafinil low                 5                   3.531273
                                                              6                  -4.798235
                                                              7                  -2.661301
                                                              8                   7.026998
                                                              9                   5.624170

behavior_name                                                                          2    \
approach     segmenter phase    treatment uniform_dosage_term treatment_mouse_id
density      moseq     Solitary bupropion high                10                  0.000000
                                                              11                  0.000000
                                                              12                  0.001083
                                                              1                   0.000000
                                                              2                   0.000000
...                                                                                    ...
rescaled_pca scalars   Solitary modafinil low                 5                   7.282144
                                                              6                   2.035397
                                                              7                   2.688457
                                                              8                   4.137132
                                                              9                   0.687523

behavior_name                                                                          3    \
approach     segmenter phase    treatment uniform_dosage_term treatment_mouse_id
density      moseq     Solitary bupropion high                10                  0.000056
                                                              11                  0.000000
                                                              12                  0.000000
                                                              1                   0.000000
                                                              2                   0.000000
...                                                                                    ...
rescaled_pca scalars   Solitary modafinil low                 5                  -3.111894
                                                              6                   2.029296
                                                              7                   1.046743
                                                              8                  -3.489477
                                                              9                  -1.722931

behavior_name                                                                          4    \
approach     segmenter phase    treatment uniform_dosage_term treatment_mouse_id
density      moseq     Solitary bupropion high                10                  0.055782
                                                              11                  0.014140
                                                              12                  0.063922
                                                              1                   0.024030
                                                              2                   0.023641
...                                                                                    ...
rescaled_pca scalars   Solitary modafinil low                 5                   1.885711
                                                              6                   4.240917
                                                              7                   4.905103
                                                              8                   3.605503
                                                              9                   1.463649

behavior_name                                                                          5    \
approach     segmenter phase    treatment uniform_dosage_term treatment_mouse_id
density      moseq     Solitary bupropion high                10                  0.008612
                                                              11                  0.005500
                                                              12                  0.014668
                                                              1                   0.005917
                                                              2                   0.010640
...                                                                                    ...
rescaled_pca scalars   Solitary modafinil low                 5                   1.362983
                                                              6                   1.526524
                                                              7                  -0.051005
                                                              8                  -1.713402
                                                              9                  -0.080013

behavior_name                                                                          6    \
approach     segmenter phase    treatment uniform_dosage_term treatment_mouse_id
density      moseq     Solitary bupropion high                10                  0.000611
                                                              11                  0.000000
                                                              12                  0.001361
                                                              1                   0.000417
                                                              2                   0.001250
...                                                                                    ...
rescaled_pca scalars   Solitary modafinil low                 5                  -1.550745
                                                              6                  -1.128797
                                                              7                  -1.716624
                                                              8                   2.834213
                                                              9                   1.026147

behavior_name                                                                          7    \
approach     segmenter phase    treatment uniform_dosage_term treatment_mouse_id
density      moseq     Solitary bupropion high                10                  0.001306
                                                              11                  0.001306
                                                              12                  0.009362
                                                              1                   0.000667
                                                              2                   0.003278
...                                                                                    ...
rescaled_pca scalars   Solitary modafinil low                 5                   0.398527
                                                              6                   0.184282
                                                              7                   0.028654
                                                              8                  -1.563585
                                                              9                  -1.350160

behavior_name                                                                          8    \
approach     segmenter phase    treatment uniform_dosage_term treatment_mouse_id
density      moseq     Solitary bupropion high                10                  0.000000
                                                              11                  0.000000
                                                              12                  0.000000
                                                              1                   0.000083
                                                              2                   0.000000
...                                                                                    ...
rescaled_pca scalars   Solitary modafinil low                 5                   2.445927
                                                              6                  -2.228824
                                                              7                  -2.216358
                                                              8                  -0.006913
                                                              9                  -0.451614

behavior_name                                                                          9    \
approach     segmenter phase    treatment uniform_dosage_term treatment_mouse_id
density      moseq     Solitary bupropion high                10                  0.025752
                                                              11                  0.092008
                                                              12                  0.025808
                                                              1                   0.018668
                                                              2                   0.023363
...                                                                                    ...
rescaled_pca scalars   Solitary modafinil low                 5                  -0.635961
                                                              6                   0.291715
                                                              7                   0.224401
                                                              8                  -0.135789
                                                              9                  -0.847022

behavior_name                                                                     ...  \
approach     segmenter phase    treatment uniform_dosage_term treatment_mouse_id  ...
density      moseq     Solitary bupropion high                10                  ...
                                                              11                  ...
                                                              12                  ...
                                                              1                   ...
                                                              2                   ...
...                                                                               ...
rescaled_pca scalars   Solitary modafinil low                 5                   ...
                                                              6                   ...
                                                              7                   ...
                                                              8                   ...
                                                              9                   ...

behavior_name                                                                     256  \
approach     segmenter phase    treatment uniform_dosage_term treatment_mouse_id
density      moseq     Solitary bupropion high                10                  NaN
                                                              11                  NaN
                                                              12                  NaN
                                                              1                   NaN
                                                              2                   NaN
...                                                                               ...
rescaled_pca scalars   Solitary modafinil low                 5                   NaN
                                                              6                   NaN
                                                              7                   NaN
                                                              8                   NaN
                                                              9                   NaN

behavior_name                                                                     257  \
approach     segmenter phase    treatment uniform_dosage_term treatment_mouse_id
density      moseq     Solitary bupropion high                10                  NaN
                                                              11                  NaN
                                                              12                  NaN
                                                              1                   NaN
                                                              2                   NaN
...                                                                               ...
rescaled_pca scalars   Solitary modafinil low                 5                   NaN
                                                              6                   NaN
                                                              7                   NaN
                                                              8                   NaN
                                                              9                   NaN

behavior_name                                                                     258  \
approach     segmenter phase    treatment uniform_dosage_term treatment_mouse_id
density      moseq     Solitary bupropion high                10                  NaN
                                                              11                  NaN
                                                              12                  NaN
                                                              1                   NaN
                                                              2                   NaN
...                                                                               ...
rescaled_pca scalars   Solitary modafinil low                 5                   NaN
                                                              6                   NaN
                                                              7                   NaN
                                                              8                   NaN
                                                              9                   NaN

behavior_name                                                                     259  \
approach     segmenter phase    treatment uniform_dosage_term treatment_mouse_id
density      moseq     Solitary bupropion high                10                  NaN
                                                              11                  NaN
                                                              12                  NaN
                                                              1                   NaN
                                                              2                   NaN
...                                                                               ...
rescaled_pca scalars   Solitary modafinil low                 5                   NaN
                                                              6                   NaN
                                                              7                   NaN
                                                              8                   NaN
                                                              9                   NaN

behavior_name                                                                     260  \
approach     segmenter phase    treatment uniform_dosage_term treatment_mouse_id
density      moseq     Solitary bupropion high                10                  NaN
                                                              11                  NaN
                                                              12                  NaN
                                                              1                   NaN
                                                              2                   NaN
...                                                                               ...
rescaled_pca scalars   Solitary modafinil low                 5                   NaN
                                                              6                   NaN
                                                              7                   NaN
                                                              8                   NaN
                                                              9                   NaN

behavior_name                                                                     261  \
approach     segmenter phase    treatment uniform_dosage_term treatment_mouse_id
density      moseq     Solitary bupropion high                10                  NaN
                                                              11                  NaN
                                                              12                  NaN
                                                              1                   NaN
                                                              2                   NaN
...                                                                               ...
rescaled_pca scalars   Solitary modafinil low                 5                   NaN
                                                              6                   NaN
                                                              7                   NaN
                                                              8                   NaN
                                                              9                   NaN

behavior_name                                                                     262  \
approach     segmenter phase    treatment uniform_dosage_term treatment_mouse_id
density      moseq     Solitary bupropion high                10                  NaN
                                                              11                  NaN